module.exports = {
    MAX_IMAGES_PER_PRODUCT: 5,
    MAX_FILE_SIZE_MB: 5,
    MAX_FILES_PER_UPLOAD: 5,
    PASSWORD_MIN_LENGTH: 6,
    JWT_EXPIRY: '1d',
    VERIFICATION_TOKEN_EXPIRY_HOURS: 24,
    RESET_TOKEN_EXPIRY_HOURS: 1,
    DEFAULT_PAGE_SIZE: 10,
    MAX_PAGE_SIZE: 50
};